[IMP] Backup almost ALL DB's

diff --git a/server/daemons/backup_local b/server/daemons/backup_local
--- a/server/daemons/backup_local
+++ b/server/daemons/backup_local
@@ -3,18 +3,15 @@
 bk_dir="/backups/local/"
 date=`date +%Y_%m_%d`
 exp_days=30
-dbs=`psql -l -t | cut -d'|' -f1 | sed -e 's/ //g' -e '/^$/d'`
-to_backup=`cat /backups/to_backup_local`
+dbs=`psql -l -w -U postgres | grep UTF8 | grep -v postgres | grep -v template0 | grep -v template1 | grep -v TEST | grep -v demo | grep -v test | grep -v desa_* |cut -d" " -f2`
 log='/var/log/odoo/backups_local.log'
 
 for db in $dbs; do
-  if [[ ${to_backup[*]} =~ $db ]] ; then 
-    pg_dump -Ft $db > $bk_dir$db\_$date.tar
-    if [ `echo $?` == 0 ];then
-        echo "DONE - $db at $date" >> log
-    else
-        echo "FAIL - $db at $date" >> log
-    fi
+  pg_dump -Ft $db > $bk_dir$db\_$date.tar
+  if [ `echo $?` == 0 ];then
+      echo "DONE - $db at $date" >> log
+  else
+      echo "FAIL - $db at $date" >> log
   fi
 done
 
